@startuml
title Диаграмма деятельности: Подбор ТСР для ребёнка с ДЦП (AS-IS)

start

:Регистрация пациента;
:Первичный осмотр врачом-реабилитологом;
:Назначение обследований;
:Сбор анамнеза и данных функционального состояния;
:Заполнение карты нарушений;

:Консилиум специалистов;
:Анализ потребностей пациента;
:Ручной подбор технических средств;

:Опробование ТСР с ребёнком;
if (Подходит ли ТСР?) then (Да)
  :Формирование заключения;
else (Нет)
  :Корректировка подбора;
  --> :Опробование ТСР с ребёнком;
endif

:Передача рекомендаций родителям;
:Документация для закупки/оформления;

stop
@enduml
