@startuml
participant Пациент
participant Врач
participant Инженер
database "Карта пациента"
database "Журнал ТСР"

Пациент -> Врач : Анкета
Врач -> Инженер : Рекомендации
Инженер -> Врач : Подтверждение ТСР
Врач -> "Карта пациента" : Обновление
Врач -> "Журнал ТСР" : Запись результата

@enduml
