@startuml
class Пациент {
  +ID: int
  +ФИО: string
  +Возраст: int
  +ФормаДЦП: string
  +УровеньGMFCS: string
  +получитьНарушения(): List<Нарушение>
  +получитьРекомендации(): List<Рекомендация>
}

class Нарушение {
  +ID: int
  +Тип: string
  +Описание: string
  +описать(): string
}

class ТСР {
  +ID: int
  +Тип: string
  +МаксВес: float
  +СовместимостьGMFCS: string
  +СовместимостьФормаДЦП: string
  +подходитДля(пациент: Пациент): bool
}

class Рекомендация {
  +ID: int
  +Дата: date
  +Автор: string
  +ПациентID: int
  +сформироватьОтчёт(): PDF
  +добавитьТСР(tsr: ТСР): void
}

class Пользователь {
  +ID: int
  +Имя: string
  +Роль: string
  +создатьРекомендацию(пациент: Пациент): Рекомендация
}

Пациент "1" -- "0..*" Нарушение : имеет
Пациент "1" -- "0..*" Рекомендация : получает
Рекомендация "1" -- "1..*" ТСР : включает
Рекомендация "1" <-- "0.." Пользователь : создаёт
@enduml
