@startuml
!define RECTANGLE class

actor Пациент
actor Врач
actor Инженер

participant "ИС подбора ТСР" as IS
database "База данных пациентов" as DBP
database "База знаний / правил" as KB
database "Журнал ТСР" as LOG

Пациент --> Врач : Анкета / жалобы
Врач --> IS : Клинические данные пациента
IS --> KB : Запрос рекомендаций
IS --> DBP : Сохранение данных пациента
IS --> Врач : Список рекомендованных ТСР

Врач --> Инженер : Подтверждение/уточнение ТСР
Инженер --> Врач : Финальное одобрение

Врач --> LOG : Финальное заключение по ТСР
@enduml
