@startuml
left to right direction

actor "Врач-реабилитолог" as Doctor
actor "Инженер по ТСР" as Engineer
actor "Администратор базы знаний" as Admin

rectangle "Система ИИ подбора ТСР" {
  together {
    together {
        usecase "Формировать и печатать отчёт" as UC5
        usecase "Выбрать ТСР" as UC4
        usecase "Просмотреть обоснования" as UC3
        usecase "Получить список ТСР" as UC2
        usecase "Ввести параметры пациента" as UC1
    }
    usecase "Просмотреть тех. параметры" as UC6
    usecase "Добавить новый кейс" as UC7
    usecase "Изменить / добавить правила" as UC8
  }
}

Doctor --> UC1
Doctor --> UC2
Doctor --> UC3
Doctor --> UC4
Doctor --> UC5

Engineer --> UC6

Admin --> UC7
Admin --> UC8

@enduml
