@startuml
|Врач|
start
:Получение медицинских данных пациента;
:Назначение реабилитационного обследования;

|Пациент/Родитель|
:Проходит обследование;
:Заполняет анкету и предоставляет информацию;

|Врач|
:Формирует профиль пациента;

|Интеллектуальная система|
:Анализирует профиль пациента;
:Формирует список рекомендуемых ТСР;

|Врач|
:Оценивает рекомендации системы;

|Техник по ТСР|
:Проверяет наличие и совместимость ТСР;
:Подбирает подходящие модели;

|Врач|
:Утверждает подбор;
:Проводит инструктаж с родителями;

|Пациент/Родитель|
:Получает и тестирует ТСР;
stop
@enduml
